adresar    <-adresar kde jsou potrebna data

textura1   <-nazvy textur
textura2
...
texturax

objekty1   <-nazvy objektu
objekty2
...
objektyx

{kazdej level bude obsahot nasledujici soubory: (+pr.: kobky)

inicializacni soubor:                  kobky.ini (txt)
mapu:                                  kobka.map (gif)
textury:                                ... .tex (gif)
objekty:                                ... .obj (gif)
