1234567890 0987654321
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ

Tento text bude zakodovan a tim padem schovan pro ruzne nenechavce
jako jsem ja a jini.
Tento koder v teto verzi pracuje s posunutim ascii o 128 znaku.
Pracuje se na dalsich kodovacich rezimech.
Texty jsou delany s extenzi PAS,protoze se stejne budou psat v TP.
Neni totiz dobre,bud vyjizdet do nejakyho editoru nebo v TP furt
prepisovat extenxi
Tento text bude zakodovan a tim padem schovan pro ruzne nenechavce
jako jsem ja a jini.
Tento koder v teto verzi pracuje s posunutim ascii o 128 znaku.
Pracuje se na dalsich kodovacich rezimech.
Texty jsou delany s extenzi PAS,protoze se stejne budou psat v TP.
Neni totiz dobre,bud vyjizdet do nejakyho editoru nebo v TP furt
prepisovat extenxi
Tento text bude zakodovan a tim padem schovan pro ruzne nenechavce
jako jsem ja a jini.
Tento koder v teto verzi pracuje s posunutim ascii o 128 znaku.
Pracuje se na dalsich kodovacich rezimech.
Texty jsou delany s extenzi PAS,protoze se stejne budou psat v TP.
Neni totiz dobre,bud vyjizdet do nejakyho editoru nebo v TP furt
prepisovat extenxi

1234567890 0987654321
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ

